### ISSUE TITLE
YAP1 connections: exploration for MorphMap paper (ORF but need to check CRISPR)

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/2023_12_JUMP_data_only_vignettes#10]
From the file in issue #7  [MorphMap_gene_gene_scoring_data_with_CRISPR.xlsx](https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/files/13844874/MorphMap_gene_gene_scoring_data_with_CRISPR.xlsx)
... we see several tabs of YAP1 connections. 
Anne should explore these.

**Comment by niranjchandrasekaran** [comment]
We will discuss the exploration of the story in [this doc](https://docs.google.com/document/d/1zKkDpBWbb3NnQhlX34LEWuuZxy5Rotre5uuuBMTxvxY/edit?usp=sharing) (private link)

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/7c68842a1b85383f683b3bfdcf21fa5b67121c10/07.compute-cosine-similarities/17.explore-YAP1-connections.ipynb)

Here are the top 10 similar and dissimilar genes to YAP1 in the ORF dataset that have a low score in the KG. The values in the heatmap are the KG values. YAP1 is not present in the CRISPR dataset.

![ORF-connections-AHDC1-B4GAT1-CNN1-CNN2-CORO2A-CORO2B-DELE1-FUT8-GRK2-INSYN1-LCOR-MYCT1-P2RX2-RNF19B-RTKN-SCAMP1-STK17A-SYT1-VGLL3-VGLL4-YAP1](https://github.com/user-attachments/assets/85b966f0-0e2a-4819-bd37-a2fa6238e9fe)

Many genes that seem to have similar names, somehow score poorly in KG, like CNN1 and CNN2. I am not sure why that happens.

Here are the coexpression values for these genes

![YAP1-similar-dissimilar-coexpression](https://github.com/user-attachments/assets/cd66776a-fa8d-4a3e-998b-e34e62fe12cc)

The coexpression values don't correlate strongly with the cosine similarity values.

![YAP1-similarity-coexpression](https://github.com/user-attachments/assets/7fd81d64-31b6-4a94-975f-73acd5528c3d)

**Comment by AnneCarpenter** [comment]
I re-digested the whole thread, esp your May 24 message, and realized we can use mRNA data in three ways and I’m not sure which you did:
1- does gene X change in expression when YAP1 is perturbed? 
2- does the pattern of mRNA expression levels when gene X is perturbed match the matter seen when YAP1 is perturbed?
3- does gene X expression change in a similar way as YAP1 expression across a bunch of perturbations?

Sounds like the coexpression data you used before was looking for (3)? (Or maybe 2?) And that the “absolute cosine similarity” was a success among known YAP connections because the entire top bar (YAP1) is blue, meaning there is strong similarity of all these genes’ coexpression with YAP1? Not sure why Absolute coexpression value is so much less dramatic. Then, for the unknown connections, we again see a pretty decent blue bar across top. Oh hang on, I think absolute cosine similarity refers to morph whereas absolute coexpression values refers to mRNA?? That makes more sense why you called this a dud, then!

I think I trust the Penn data as being much more relevant so we should do that analysis, but IIUC we can only look for (1) because we only have a subset of mRNA values. I think I would prioritize their first dataset (gene expression microarray dataset from murine UPS tumors (Yap KO vs. Yap WT)) rather than their second (KP230 cell NB4A) but running both is great if convenient.

If it's still true that the 3 most high-morph and low-KG are CORO2A, CORO2B and GMIP we could look at their images & features.

We should also do a plate layout analysis here. I see INSYN1 in this set which is making me a bit nervous since it showed up in several other clusters (seems to be cancer related so could be general tox/cell growth phenotype).

A comment made above that is likely to go into the paper since it seems still true is this:
In the top ORF links we see connection of YAP1 to 9 actin binding proteins (enrichment pval=10^-5, CORO2A, CORO2B, CNN1, CNN2, WASL...) and 10 protein serine/threonine kinases (pval=10^-7, PRKCE, PRKD1, MAP2K6, PAK5, STK17A, GRK2, etc.). From KG scoring, connection of YAP1 to protein kinases looks "explained" while connection to actin binding is "not explained”.

For the paper we will want the heatmap to show the known + unknown so we can comment on both (and feel reassured that some strong known ones are there - which sounds like “WWTR1 is the second-strongest similar, and there are some STK's and CDC and TRAF genes too (different isoforms apparently).” (From my notes above).

**Comment by niranjchandrasekaran** [comment]
> Sounds like the coexpression data you used before was looking for (3)? (Or maybe 2?) And that the “absolute cosine similarity” was a success among known YAP connections because the entire top bar (YAP1) is blue, meaning there is strong similarity of all these genes’ coexpression with YAP1? Not sure why Absolute coexpression value is so much less dramatic. Then, for the unknown connections, we again see a pretty decent blue bar across top. 

Yes, the coexpression data I am using is looking for 3 (https://academic.oup.com/nar/article/51/D1/D80/6814455). 

> Oh hang on, I think absolute cosine similarity refers to morph whereas absolute coexpression values refers to mRNA?? That makes more sense why you called this a dud, then!

That's right.

> I think I trust the Penn data as being much more relevant so we should do that analysis, but IIUC we can only look for (1) because we only have a subset of mRNA values. I think I would prioritize their first dataset (gene expression microarray dataset from murine UPS tumors (Yap KO vs. Yap WT)) rather than their second (KP230 cell NB4A) but running both is great if convenient.

I believe the file that was previously shared only contains the expression levels for a handful of genes that we were previously interested in. Can I get the whole dataset?

> If it's still true that the 3 most high-morph and low-KG are CORO2A, CORO2B and GMIP we could look at their images & features.

 Will do.

> We should also do a plate layout analysis here. I see INSYN1 in this set which is making me a bit nervous since it showed up in several other clusters (seems to be cancer related so could be general tox/cell growth phenotype).

Will do.

> For the paper we will want the heatmap to show the known + unknown so we can comment on both (and feel reassured that some strong known ones are there - which sounds like “WWTR1 is the second-strongest similar, and there are some STK's and CDC and TRAF genes too (different isoforms apparently).” (From my notes above).

Sounds good.

**Comment by AnneCarpenter** [comment]
I've asked Penn!

**Comment by AnneCarpenter** [comment]
"Here's the mouse tumor dataset. The dataset is publicly available (NCBI GEO: GSE109920). Columns K-T represent tumors from individual mice. Fold changes in column H show KP (control) vs. KPY (Yap1 knockout). Recall that the knockout is only in UPS cells, so the other cell types in the tumor do express Yap1."
[KP vs. KPY tumor differential expression_5309results.xlsx](https://github.com/user-attachments/files/16770711/KP.vs.KPY.tumor.differential.expression_5309results.xlsx)

I'm not sure if this suffices to address the analysis; if not LMK! @niranjchandrasekaran

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/212540076ad9462c382162868a7b5683e703b803/07.compute-cosine-similarities/17.1.YAP1-cluster-images-and-feature-analysis.ipynb)

Here are the results from the feature group similarity analysis and the cell images of the four genes. Similarity of the four genes is primarily due to nuclear features.

![YAP1_subset_area_size_compartment](https://github.com/user-attachments/assets/39cca316-5a48-4b21-b24a-f730c102afd1)

![YAP1_subset_feature_group_channel](https://github.com/user-attachments/assets/04cfe787-17dc-45f3-a764-5a03f70d5982)

![facet_grid_montage_YAP1](https://github.com/user-attachments/assets/6ef1daed-3d4c-4e84-be41-a119bb2c4a6a)

---

[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/212540076ad9462c382162868a7b5683e703b803/07.compute-cosine-similarities/17.0.explore-YAP1-connections.ipynb)

Plate layout of the YAP1 cluster looks fine. 

![ORF-plate-layout-YAP1](https://github.com/user-attachments/assets/1026c4bc-6c8d-43df-972c-62a1dd70c152)

**Comment by niranjchandrasekaran** [comment]
> I'm not sure if this suffices to address the analysis; if not LMK! 

Will take a look.

**Comment by AnneCarpenter** [comment]
Awesome, rarely do we see such a clear feature analysis outcome! 
Could we add neg controls from the same plate as YAP1 to the picture grid, to compare visually? And I assume the analysis was "how are this group of 4 different from neg control"?

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/a656b70a6ac8312baa703a085af6e9397ba9b53a/07.compute-cosine-similarities/17.0.explore-YAP1-connections.ipynb)

The fold change values look better compared to the coexpression values against phenotypic cosine similarity (R^2 is still only 0.06). The right most point is `CORO2A`.

![YAP1-similarity-fold-change](https://github.com/user-attachments/assets/2a5c8aef-2c30-4659-853f-1f6d14e2201d)

**Comment by AnneCarpenter** [comment]
What data points are shown in this plot? It's clearly a subset but seems to include some not-strong correlators so I wondered.

**Comment by AnneCarpenter** [comment]
If it's the top 10 similar and dissimilar genes to YAP1 in the ORF dataset that have a low score in the KG, then it'd be great to show which points are similar and which are dissimilar, and also to show which are pos and neg fold change (maybe color for one and shape for the other?) so we can see the directionality. Or you could just show non-absolute for both axes and maybe we can get a view of what's going on. 

Overall, looks like maximum is 50% fold change?

**Comment by niranjchandrasekaran** [comment]
>  What data points are shown in this plot? It's clearly a subset but seems to include some not-strong correlators so I wondered.

Similarity of YAP1 to other genes (absolute cosine similarity) and fold change of that gene's expression when YAP1 is knocked out (absolute fold change). These are all top 10 similar and dissimilar genes in https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/10#issuecomment-2303137892. 

> If it's the top 10 similar and dissimilar genes to YAP1 in the ORF dataset that have a low score in the KG, then it'd be great to show which points are similar and which are dissimilar, and also to show which are pos and neg fold change (maybe color for one and shape for the other?) so we can see the directionality. Or you could just show non-absolute for both axes and maybe we can get a view of what's going on.

Will do.

**Comment by niranjchandrasekaran** [comment]
[Notebook 2](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/5a9fa01585aac0dfa5fe6bef84d72017d0097a49/07.compute-cosine-similarities/17.1.YAP1-cluster-images-and-feature-analysis.ipynb)

Going back to the small YAP1 cluster (YAP1, CORO2A, CORO2B and GMIP)

> Could we add neg controls from the same plate as YAP1 to the picture grid, to compare visually? 

Here is the updated grid.

![facet_grid_montage_YAP1](https://github.com/user-attachments/assets/46925c6e-b814-4c62-aede-98c3fd8ebad0)

LUCIFERASE is from a same plate as YAP1.

> And I assume the analysis was "how are this group of 4 different from neg control"?

In https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/10#issuecomment-2316050008, I was showing the median cosine similarity of the “mini” profiles of the four genes. I wasn't comparing them to negative control, though they all have a phenotype and therefore are different from negative control.

To report which features distinguish the cluster from negative control, I computed the average number of features per channel that were significantly different from negative control. Even here, most features are DNA features.

| cluster   |   ER_percent |   Mito_percent |   DNA_percent |   AGP_percent |   RNA_percent |
|:----------|-------------:|---------------:|--------------:|--------------:|--------------:|
| YAP1      |     0.225597 |       0.063449 |      0.322668 |      0.197397 |      0.190889 |

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/8dc8640092b63950a7a39333fd49f02d9ff498dd/07.compute-cosine-similarities/17.0.explore-YAP1-connections.ipynb)

> Or you could just show non-absolute for both axes and maybe we can get a view of what's going on.

![YAP1-similarity-fold-change_directionality](https://github.com/user-attachments/assets/c167c9b6-e6de-4b7a-af1f-b3b938b78081)

**Comment by AnneCarpenter** [comment]
Great, thank you - does one-fold change here mean it's actually not a change at all? (ie values between -1 and 1 are impossible)

**Comment by AnneCarpenter** [comment]
I found the answer in the raw data file: there are no values between -1 and 1, which means most of the values for our set of top/bottom 10 genes are not remarkable. I will ask the data providers how we might tell if, say, 1.5 is remarkable.
 
We discussed today in checkin: we don't trust the feature analyses in this thread very much:
One is based on "what do these 4 genes have in common"- if all profiles are normalized to neg controls, then I suppose this means whatever signal is leftover is probably what makes the genes distinct from neg controls, but I'm not certain - and the fact that it points to DNA features but all genes (except GMIP1) look very similar to the neg control in the DNA channel makes me suspicious. We've never done this analysis so it's hard to be confident that this is a unique result.

The other is based on "what % of features in each category are significantly different for each of the 4 genes (or collectively)" but with feature selection the categories may have different proportions of strong vs weak features, making this potentially confounded.

PLus, it's all confounded by the fact that we are not using the final profiles but instead the one just before the steps where feature names become meaningless. 
Altogether, this makes us pretty cautious. For this cluster, since Mohammad spent so mcuh time thinking about this cluster and looking at images using the enriched single-cell analysis, it's probably better to go back to Rohban, Fuller et al Cell Systems 2022 and just read in plain text how YAP1 was distinctive and then see if we can see it by eye here in the images.

**Comment by AnneCarpenter** [comment]
I will followup on the above. 
In the meantime, are we confident about the KG values? I see they are very low between pairs w similar names: 
VGLL3/4
CORO2A/B
CNN1/2
I'm suspicious that the KG doesn't see any of those pairs as likely strongly related!

**Comment by niranjchandrasekaran** [comment]
> In the meantime, are we confident about the KG values? I see they are very low between pairs w similar names:
> VGLL3/4
> CORO2A/B
> CNN1/2
> I'm suspicious that the KG doesn't see any of those pairs as likely strongly related!

I was confused about this as well. I checked the files that Evotec shared with me and these seem to the KG values.

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/c0f4968ad6fcd9bb956c1b249f4ddbb1faa25c58/07.compute-cosine-similarities/18.0.KG-sanity-check.ipynb)

Just a sanity check to ensure that the KG values of those pairs of genes are indeed low.

| gene_1   | gene_2   |   gene_mf |   gene_bp |   gene_pathway |
|:---------|:---------|----------:|----------:|---------------:|
| CNN1     | CNN2     |     0.259 |     0.286 |          0.31  |
| CORO2B   | CORO2A   |     0.343 |     0.236 |          0.187 |
| VGLL3    | VGLL4    |     0.064 |     0.081 |          0.088 |

**Comment by AnneCarpenter** [comment]
My colleague got back to me: fold change can be subject to noise so she recommends using Q values instead (these will not be directional but I suppose you can add neg and pos sign to it depending on the direction of fold change). I looked up a few of our strongest-morph-similarity genes and they were not significant by q value but if you could re-do the scatterplot using that comlumn instead of fold change it would be more systematic to confirm whether there's truly nothing interesting to point out in this raw data.

"q-value is the metric for statistical significance. Q-values are just p-values corrected for the false discovery rate (5%).

You're correct that the fold-change computation is a little more complex than KP/KPY. They were computed using "Significance Analysis of Microarrays" (SAM), which was the gold-standard method for differential gene expression analysis in two-color probe-based microarrays. A bioinformatics expert did this particular analysis since it preceded my arrival at Penn by several years, but I had lots of experience with SAM in grad school and was able to back-calculate the fold changes in column H using Yap1 as an example. Essentially, the values in columns K-T are log2 values, so you have to unlog them. Then, taking the ratio of the averages (KP/KPY) gets you to within 1 decimal point of the fold-change in column H. Then a negative sign is added (-12.0 instead of 12.0) - this could be due either to a mathematical property that's escaping me or a setting in SAM. But what matters most is the interpretation: Yap1 is expressed 12-fold higher in KP tumors compared to KPY (AKA 12-fold lower in KPY compared to KP)."

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/1ded6b3670b60b736e9371976795e44e03965c2b/07.compute-cosine-similarities/17.0.explore-YAP1-connections.ipynb)

> but if you could re-do the scatterplot using that comlumn instead of fold change it would be more systematic to confirm whether there's truly nothing interesting to point out in this raw data.

I didn't plot the values because none of our genes  have a significant fold change.

| Metadata_Gene_Symbol   |   Similarity |   Metadata_qvalue |
|:-----------------------|-------------:|------------------:|
| AHDC1                  |     0.396364 |           60.3713 |
| CNN1                   |     0.476689 |           84.6134 |
| CNN2                   |     0.372812 |           84.6803 |
| CORO2A                 |     0.558896 |           65.8483 |
| CORO2B                 |     0.466192 |           84.6134 |
| FUT8                   |    -0.253937 |           87.586  |
| LCOR                   |    -0.286104 |           75.7986 |
| LCOR                   |    -0.286104 |           87.586  |
| MYCT1                  |    -0.274379 |           84.6134 |
| P2RX2                  |    -0.251989 |           65.8483 |
| RNF19B                 |     0.36091  |           84.6134 |
| RTKN                   |     0.422219 |           86.5241 |
| SCAMP1                 |    -0.258267 |           87.586  |
| SYT1                   |     0.406036 |           87.586  |
| VGLL3                  |    -0.253174 |           87.586  |
| VGLL4                  |    -0.254708 |           65.8483 |

So, I thought I would check the cosine similarity of all the genes that show a significant fold change. Here I report the percentile of the cosine similarity values instead of the values themselves. Percentiles near 100 and 0 are the interesting ones.

| Metadata_Gene_Symbol   |   Metadata_Fold_Change |   Metadata_qvalue |   cosine_similarity_percentile |
|:-----------------------|-----------------------:|------------------:|-------------------------------:|
| CEP72                  |                1.38714 |          3.90329  |                      0.991001  |
| MTMR9                  |                1.95756 |          4.4704   |                      0.981028  |
| SPATA7                 |                1.76291 |          2.38277  |                      0.816803  |
| HNRNPDL                |                1.49019 |          0.815263 |                      0.689962  |
| ALKBH3                 |                1.28788 |          1.73065  |                      0.581412  |
| FAM107A                |                1.36986 |          2.38277  |                      0.502607  |
| TAF1B                  |                1.64345 |          3.90329  |                      0.437225  |
| TRAF6                  |                1.59328 |          0.815263 |                      0.402705  |
| RBM25                  |                2.87034 |          0        |                      0.397906  |
| TLK1                   |                1.27575 |          4.4704   |                      0.363413  |
| PER1                   |                2.53779 |          3.20803  |                      0.35923   |
| SRSF5                  |                1.49755 |          3.90329  |                      0.355995  |
| FAM117B                |                1.61891 |          1.73065  |                      0.245488  |
| MECP2                  |                1.26004 |          3.20803  |                      0.206302  |
| RBM26                  |                1.68995 |          2.38277  |                      0.165922  |
| SSBP1                  |                1.61139 |          2.38277  |                      0.0916675 |
| IL20RB                 |                1.5808  |          2.38277  |                      0.0634643 |
| YAP1                   |              -12.0403  |          0        |                      0         |


The top and bottom 2 or 3 genes are the ones that show a significant fold change and also are either similar or dissimilar to YAP1. When I checked the KG scores, they were all below 0.4. So these might be novel connections.

| gene_1   | gene_2   |   KG_score |
|:---------|:---------|-----------:|
| YAP1     | RBM26    |      0.368 |
| YAP1     | IL20RB   |      0.325 |
| YAP1     | CEP72    |      0.353 |
| YAP1     | SSBP1    |      0.388 |
| YAP1     | MTMR9    |      0.2   |
| YAP1     | SPATA7   |      0.336 |

--- 

[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/ee850524e8eb79940d9547a58710e03d769e7f21/07.compute-cosine-similarities/17.1.YAP1-cluster-images-and-feature-analysis.ipynb)

Here are cell images from our genes of interest (from https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/10#issuecomment-2303137892): [facet_grid_montage_YAP1.pdf](https://github.com/user-attachments/files/16809196/facet_grid_montage_YAP1.pdf) (Attaching a pdf because pngs aren't opening correctly).

[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/f2cc953ff7844c1b670491a960d5f7c901dffbe4/07.compute-cosine-similarities/17.2.YAP1-cluster-images.ipynb)

I also created the grid for the new cluster from above: [facet_grid_montage_YAP1_2.pdf](https://github.com/user-attachments/files/16809825/facet_grid_montage_YAP1_2.pdf)

**Comment by AnneCarpenter** [comment]
IIUC:
- You started with the all the genes with mRNA fold changes below 5% (q value, out of the ~65k rows of data, I assume you ignored the lines without a gene symbol)
- filtered those for (a) in our ORF dataset and (b) had phenotypic activity above threshold; this yielded 18 genes
- of those, 3 had significant morphology similarity to YAP1: that is more than expected by chance (5% by definition, unless the ignoring lines without a gene symbol messes that up).
- and all 3 of those have low KG values (IIUC you didn’t filter for low KG value going into this analysis):

YAP1	CEP72	0.353
YAP1	IL20RB	0.325
YAP1	MTMR9	0.2

That seems a fair analysis to do, and yielding more than expected by chance!

And you did this because:
- starting with the genes that had high morph similarity to YAP1 (also filtered for phenotypic activity)
- yielded zero genes with significant mRNA fold changes (by q value)

By eye I would say that YAP1/CEP72/MTMR9 have more sparkly AGP whereas luciferase/IL20RB are more blobby. I don’t notice differences in other channels. This could be due to the images being blurry vs sharp so we should check plate layout for this new set of 4 genes CEP72, YAP1, IL20RB, MTMR9

**Comment by niranjchandrasekaran** [comment]
[Notebook](https://github.com/jump-cellpainting/2024_Chandrasekaran_Morphmap/blob/5f020d934d6966aa0fabe7bbc7e914805a37ead1/07.compute-cosine-similarities/17.2.YAP1-cluster-images.ipynb)

CEP72 and IL20RB are the in the same well position in two different plates in the same batch. But none of the genes are on the same well position or same plate/batch as YAP1.

![ORF-plate-layout-YAP1_2](https://github.com/user-attachments/assets/5ea8ce85-dfd9-4e5c-815c-3d4dca28b75a)

**Comment by niranjchandrasekaran** [comment]
Regarding https://github.com/broadinstitute/2023_12_JUMP_data_only_vignettes/issues/10#issuecomment-2318837076, @auranic said the following.

> Firstly, our current approach consists in predicting the protein function and not protein family. The knowledge graph that we use does not have explicit information about the content of protein families and is blind to their naming.
> 
> As you see in the slides the pairs that you mentioned are not that closely related accordingly to STRING: only a weak co-citation relation for VGLL3/4, no physical interactions, no strong co-expression, etc.
> 
> We also verified the co-citation using the most recent version of Pubtator (and Pubtator data prior to 2020 was included in DRKG knowledge graph). I would characterize the literature connection between these pairs of proteins as weak.
> 
> For example, CORO2A and CORO2B proteins have been co-cited in 13 publications, most of them after 2020, most of co-citations are just listing coronins as a family.  The physical interaction between CORO2A and CORO2B has been reported only in Bioplex 2.0 resource and was included in IntAct with MI-Score 0.35 (which is low) and by association (by coip and via “complex expansion”) – this is why it is probably not included into STRING DB. CORO2A and CORO2B are connected in the DRKG knowledge graph only through very generic Gene Ontologies, the most specific of which is ‘actin binding’. No common diseases, Anatomy, Compounds or Pathways, etc. The tissue expression pattern for this pair of genes seems to be quite different. Therefore, it is not surprising that the resulting KG score for them is low (0.343). You can see that for some other coronin pairs the KG score is higher (eg, CORO1A/B=0.779, CORO1B/2A=0.564, CORO2A/1A=0.522).
>  
> Of note, for CNN1/2 pair Pubtator mixes CNN with Convolutional Neural Network abbreviation which results in 132 cocitations but most of them are false positives.
> 
> Out of curiosity, I also made a global analysis of all pairs of similar protein names (most probably belonging to the same family). It shows that only roughly for half of such pairs one can expect an “explained” by KG score connection (>0.5), while for another half the KG score can be low, and this largely depends on the family. Eg, for Zinc fingers (ZNF), most of the pairs are not functionally related, while for MAPK family, all the pairs are very strongly connected. Another example, soluble carriers (SLC) seem to be relatively well connected but with a fraction of pairs characterized by a low KG score. Coronins (CORO) in this sense take somehow intermediate position (a bit less coherent than keratins – KRT, for example).

This assures us that the KG values that we have are what we would expect them to be.

[2024_0902_Evotec_KGinFamilies.pptx](https://github.com/user-attachments/files/16852282/2024_0902_Evotec_KGinFamilies.pptx)

**Comment by jgaetz-plex** [comment]
Analyzing the top 50 genes most similar to YAP1 in the ORF dataset using the Plex web application, we identified four other known known Hippo pathway components within this group, namely WWTR1 (TAZ), STK3 (MST2), VGLL4, and PRKCE ([Fu et al. ](https://pubmed.ncbi.nlm.nih.gov/36347846/)[2022](https://pubmed.ncbi.nlm.nih.gov/36347846/); [Gong et al. 2015](https://pubmed.ncbi.nlm.nih.gov/26206313/)). Notably, WWTR1 (TAZ), which shares significant functional and structural similarity with YAP1, was the second-strongest similar gene in the ORF dataset ([Plouffe et al. 2018](https://pubmed.ncbi.nlm.nih.gov/29802201/); [LeBlanc et al. 2021](https://pubmed.ncbi.nlm.nih.gov/33582842/)). Additionally, perturbations of genes or pathways involved in neuronal development were also found to modulate a subset the top 50 YAP1-similar genes. For example, knockout of the neural crest regulator SNAI2 resulted in downregulation of 12 of these genes in neuroblastoma ([Vrenken et al. 2019](https://pubmed.ncbi.nlm.nih.gov/31862304/)), knockdown of the amyotrophic lateral sclerosis (ALS) gene TDP43 induced downregulation of 11 of these genes in mouse striatum ([Kapeli](https://pubmed.ncbi.nlm.nih.gov/27378374/) [et](https://pubmed.ncbi.nlm.nih.gov/27378374/) [al.](https://pubmed.ncbi.nlm.nih.gov/27378374/) [2016](https://pubmed.ncbi.nlm.nih.gov/27378374/)), knockdown of the HOXA1, a gene known to regulate neural cell fate, downregulated 10 of these genes in lung fibroblasts, and alcohol consumption was associated with misregulation of 11 of these genes in postmortem human hippocampus ([McClintick et al. 2013](https://pubmed.ncbi.nlm.nih.gov/23981442/)).

**Comment by jgaetz-plex** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/gaetz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/gaetz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


AHDC1
--
ARHGAP29
ARHGEF9
BAALC
CDRT15
CNN1
CNN2
CORO2A
CORO2B
CSRNP2
DELE1
DNAJC25
FOXG1
FOXP3
GADD45G
GALNT4
GMIP
GRK2
INSYN1
LCOR
LDLRAD4
MAP2K6
MARVELD2
MMP10
MSN
MYCT1
MYLK3
NFE2L3
PLS3
PRKCE
PRKD1
PRSS1
RNF19B
RTKN
SAXO5
SCAMP1
SENP1
STK17A
STK3
SYT1
SYT2
TFAP2A
TOB1
TXNIP
UBIAD1
VCAM1
VGLL4
WWTR1
YAP1
ZNF704



</body>

</html>

**Comment by jgaetz-plex** [comment]
I have read through all of the above comments on this GitHub issue, but I'm not sure there is more to add from the above discussion.

**Comment by AnneCarpenter** [comment]
We included YAP1 in the paper so I think we can close this, right @niranjchandrasekaran ?
